// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #LibvirtVerbInput is the `libvirt` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type LibvirtVerbInput struct {
	// method — the libvirt method name (the former core #LibvirtMethod enum; the
	// verb's PRIMARY input field, so `libvirt: info` desugars to {method: "info"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// text — passwd's new graphics password / qmp's command name.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// input — qmp's optional JSON args blob.
	Input string `yaml:"input,omitempty" json:"input,omitempty"`

	// key — send-key's key/chord spec (whitespace-split into keycode slots).
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// command — guest/exec's argv (whitespace-split; absorbed from the former
	// shared #Op command modifier — authored `command:` on a step is the command
	// plugin's sugar key now).
	Command string `yaml:"command,omitempty" json:"command,omitempty"`

	// uri — libvirt connection URI override ("" → qemu:///session; the nested CLI
	// also honours CHARLY_LIBVIRT_URI).
	URI string `yaml:"uri,omitempty" json:"uri,omitempty"`

	// artifact + validators — screenshot's PNG output path and the post-run
	// artifact-reality assertions (sdk.RunArtifactValidators reads them off the input).
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	ArtifactMinCastEvents int `yaml:"artifact_min_cast_events,omitempty" json:"artifact_min_cast_events,omitempty"`
}
